WITH SHORT_LONG_LENGTH AS 
(SELECT CITY,LENGTH(CITY) AS LEN FROM STATION)
select CITY,LENGTH(CITY) FROM STATION WHERE LENGTH(CITY)=(select MIN(LEN) FROM SHORT_LONG_LENGTH) ORDER BY CITY LIMIT 1 ;


WITH SHORT_LONG_LENGTH AS 
(SELECT CITY,LENGTH(CITY) AS LEN FROM STATION)
select CITY,LENGTH(CITY) FROM STATION WHERE LENGTH(CITY)=(select MAX(LEN) FROM SHORT_LONG_LENGTH) ORDER BY CITY limit 1;